=== ripdajacker/commons-betwixt/src/test/org/apache/commons/betwixt/xmlunit/test.xsd
<?xml version='1.0'?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
	<xsd:element name='address-book'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="address" minOccurs='1' maxOccurs='unbounded'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name='address'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name='addressee' type='xsd:string'/>
				<xsd:element name='street' type='xsd:string'/>
				<xsd:element name='city' type='xsd:string'/>
				<xsd:element name='region' type='xsd:string'/>
				<xsd:element name='country' type='xsd:string'/>
				<xsd:element name='postcode' type='xsd:string'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== ripdajacker/commons-betwixt/src/test/org/apache/commons/betwixt/xmlunit/valid.xml
<?xml version='1.0'?>
<address-book
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation='test.xsd'>
	<address>
		<addressee>Chippy Minton</addressee>
		<street>14, The High Street</street>
		<city>Trumpton</city>
	    <region>Trumptonshire</region>
		<country>UK</country>
		<postcode>TP2 5TY</postcode>
	</address>
	<address>
		<addressee>Mr Clamp</addressee>
		<street>1, Green Lane</street>
		<city>Trumpton</city>
	    <region>Trumptonshire</region>
		<country>UK</country>
		<postcode>TP2 4RS</postcode>
	</address>
	<address>
		<addressee>Mr Troop</addressee>
		<street>45, The High Street</street>
		<city>Trumpton</city>
	    <region>Trumptonshire</region>
		<country>UK</country>
		<postcode>TP2 5TY</postcode>
	</address>
    <address>
		<addressee>Barney McGrew</addressee>
		<street>4, Park Road</street>
		<city>Trumpton</city>
	    <region>Trumptonshire</region>
		<country>UK</country>
		<postcode>TP2 7TY</postcode>
	</address>
	<address>
		<addressee>Miss Lovelace</addressee>
		<street>17, The High Street</street>
		<city>Trumpton</city>
	    <region>Trumptonshire</region>
		<country>UK</country>
		<postcode>TP2 5TY</postcode>
	</address>
</address-book>
